// Generated by CoffeeScript 1.9.2
(function() {
  var Utils,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Utils = require("../Utils");

  exports.enable = function() {
    var MobileScrollFixLayer, handleScrollingLayerTouchMove, handleScrollingLayerTouchStart;
    document.ontouchmove = function(event) {
      if (event.target === document.body) {
        return event.preventDefault();
      }
    };
    handleScrollingLayerTouchMove = function(event) {
      return event.stopPropagation();
    };
    handleScrollingLayerTouchStart = function(event) {
      var element, startTopScroll;
      element = this._element;
      startTopScroll = element.scrollTop;
      if (startTopScroll <= 0) {
        element.scrollTop = 1;
      }
      if (startTopScroll + element.offsetHeight >= element.scrollHeight) {
        return element.scrollTop = element.scrollHeight - element.offsetHeight - 1;
      }
    };
    MobileScrollFixLayer = (function(superClass) {
      extend(MobileScrollFixLayer, superClass);

      function MobileScrollFixLayer(options) {
        this._updateScrollListeners = bind(this._updateScrollListeners, this);
        MobileScrollFixLayer.__super__.constructor.call(this, options);
        if (this.constructor.name === "Layer") {
          this.on("change:scrollVertical", this._updateScrollListeners);
          this._updateScrollListeners();
        }
      }

      MobileScrollFixLayer.prototype._updateScrollListeners = function() {
        if (this.scrollVertical === true) {
          this.on("touchmove", handleScrollingLayerTouchMove);
          return this.on("touchstart", handleScrollingLayerTouchStart);
        } else {
          this.off("touchmove", handleScrollingLayerTouchMove);
          return this.off("touchstart", handleScrollingLayerTouchStart);
        }
      };

      return MobileScrollFixLayer;

    })(Framer.Layer);
    return window.Layer = window.Framer.Layer = MobileScrollFixLayer;
  };

}).call(this);
