// Generated by CoffeeScript 1.9.2
(function() {
  var slice = [].slice;

  exports.enable = function(module) {
    var ClassWrapper;
    if (module == null) {
      module = window;
    }
    ClassWrapper = function(Klass) {
      return function() {
        var args;
        args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        return this.prototype = (function(func, args, ctor) {
          ctor.prototype = func.prototype;
          var child = new ctor, result = func.apply(child, args);
          return Object(result) === result ? result : child;
        })(Klass, args, function(){});
      };
    };
    module.Frame = ClassWrapper(Framer.Frame);
    module.Layer = ClassWrapper(Framer.Layer);
    module.BackgroundLayer = ClassWrapper(Framer.BackgroundLayer);
    module.VideoLayer = ClassWrapper(Framer.VideoLayer);
    return module.Animation = ClassWrapper(Framer.Animation);
  };

}).call(this);
