// Generated by CoffeeScript 1.9.2
(function() {
  var Config, Utils;

  Utils = require("./Utils");

  Config = require("./Config").Config;

  exports.Animator = (function() {
    "The animator class is a very simple class that\n	- Takes a set of input values at setup({input values})\n	- Emits an output value for progress (0 -> 1) in value(progress)";
    function Animator(options) {
      if (options == null) {
        options = {};
      }
      this.setup(options);
    }

    Animator.prototype.setup = function(options) {
      throw Error("Not implemented");
    };

    Animator.prototype.next = function(delta) {
      throw Error("Not implemented");
    };

    Animator.prototype.finished = function() {
      throw Error("Not implemented");
    };

    return Animator;

  })();

}).call(this);
