// Generated by CoffeeScript 1.9.2
(function() {
  var BackgroundLayer, Layer,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Layer = require("./Layer");

  BackgroundLayer = (function(superClass) {
    extend(BackgroundLayer, superClass);

    function BackgroundLayer(options) {
      this.bringToFront = bind(this.bringToFront, this);
      options.properties = options.properties || {};
      delete options.width;
      delete options.height;
      BackgroundLayer.__super__.constructor.call(this, options);
    }

    BackgroundLayer.prototype.bringToFront = function() {};

    return BackgroundLayer;

  })(Layer);

  module.exports = BackgroundLayer;

}).call(this);
