// Generated by CoffeeScript 1.9.2
(function() {
  var BackgroundLayer, Layer,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Layer = require("./Layer");

  BackgroundLayer = (function(superClass) {
    extend(BackgroundLayer, superClass);

    function BackgroundLayer(options) {
      options.properties = options.properties || {};
      options.width = -1;
      options.height = -1;
      BackgroundLayer.__super__.constructor.call(this, options);
    }

    return BackgroundLayer;

  })(Layer);

  module.exports = BackgroundLayer;

}).call(this);
