// Generated by CoffeeScript 1.9.2
(function() {
  var Clock, Engine, famous;

  famous = require("famous");

  Engine = famous.core.FamousEngine;

  Clock = (function() {
    function Clock() {}

    Clock.getTime = function() {
      return Engine.getClock().getTime();
    };

    return Clock;

  })();

  module.exports = Clock;

}).call(this);
