// Generated by CoffeeScript 1.9.2
(function() {
  var Color,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Color = (function(superClass) {
    extend(Color, superClass);

    function Color() {}

    return Color;

  })(BaseClass);

}).call(this);
