// Generated by CoffeeScript 1.9.2
(function() {
  var FamousPropertySetter;

  FamousPropertySetter = {
    width: function(layer) {
      var nodeValues, propertyValue;
      propertyValue = layer._properties.width;
      nodeValues = layer._node.getAbsoluteSize();
      console.log(nodeValues);
      layer._node.setAbsoluteSize(propertyValue, nodeValues[1], nodeValues[2]);
      return console.log(nodeValues);
    },
    height: function(layer) {
      var nodeValues, propertyValue;
      propertyValue = layer._properties.height;
      nodeValues = layer._node.getAbsoluteSize();
      console.log(nodeValues);
      layer._node.setAbsoluteSize(nodeValues[0], propertyValue, nodeValues[2]);
      return console.log(nodeValues);
    },
    x: function(layer) {
      var nodeValues, propertyValue;
      propertyValue = layer._properties.x;
      nodeValues = layer._node.getPosition();
      return layer._node.setPosition(propertyValue, nodeValues[1], nodeValues[2]);
    },
    y: function(layer) {
      var nodeValues, propertyValue;
      propertyValue = layer._properties.y;
      nodeValues = layer._node.getPosition();
      return layer._node.setPosition(nodeValues[0], propertyValue, nodeValues[2]);
    },
    z: function(layer) {
      var nodeValues, propertyValue;
      propertyValue = layer._properties.z;
      nodeValues = layer._node.getPosition();
      return layer._node.setPosition(nodeValues[0], nodeValues[1], propertyValue);
    },
    scale: function(layer) {
      var nodeValues, originValues, propertyValue;
      propertyValue = layer._properties.scale;
      originValues = layer._node.getOrigin();
      layer._node.setOrigin(0.5, 0.5);
      nodeValues = layer._node.getScale();
      layer._node.setScale(propertyValue, propertyValue, propertyValue);
      return layer._node.setOrigin(originValues[0], originValues[1], originValues[2]);
    },
    rotationZ: function(layer) {
      var nodeValues, propertyValue;
      propertyValue = layer._properties.rotationZ * Math.PI / 180;
      nodeValues = layer._node.getRotation();
      return layer._node.setRotation(0, 0, propertyValue);
    },
    backgroundColor: function(layer) {
      var propertyValue;
      propertyValue = layer._properties.backgroundColor;
      return layer._element.setProperty("background-color", propertyValue);
    }
  };

  module.exports = FamousPropertySetter;

}).call(this);
