// Generated by CoffeeScript 1.9.2
(function() {
  var FamousPropertySetter;

  FamousPropertySetter = {
    visible: function(layer) {
      var propertyValue;
      propertyValue = layer._properties.visible;
      if (propertyValue) {
        return layer._element.setProperty("display", "block");
      } else {
        return layer._element.setProperty("display", "none");
      }
    },
    ignoreEvents: function(layer) {
      var propertyValue;
      propertyValue = layer._properties.ignoreEvents;
      if (propertyValue) {
        return layer._element.setProperty("pointerEvents", "none");
      } else {
        return layer._element.setProperty("pointerEvents", "auto");
      }
    },
    clip: function(layer) {
      var propertyValue;
      propertyValue = layer._properties.clip;
      if (layer._properties.scrollHorizontal === true || layer._properties.scrollVertical === true) {
        layer._element.setProperty("overflow", "auto");
      }
      if (layer._properties.clip === true) {
        layer._element.setProperty("overflow", "hidden");
      }
      return layer._element.setProperty("overflow", "visible");
    },
    borderRadius: function(layer) {
      if (!_.isNumber(layer._properties.borderRadius)) {
        return layer._element.setProperty("borderRadius", layer._properties.borderRadius);
      } else {
        return layer._element.setProperty("borderRadius", layer._properties.borderRadius);
      }
    },
    opacity: function(layer) {
      var propertyValue;
      propertyValue = layer._properties.opacity;
      return layer._element.setOpacity(propertyValue);
    },
    index: function(layer) {
      var propertyValue;
      propertyValue = layer._properties.index;
      return layer._element.setProperty("zIndex", propertyValue);
    },
    color: function(layer) {
      var propertyValue;
      propertyValue = layer._properties.color;
      return layer._element.setProperty("color", propertyValue);
    },
    width: function(layer) {
      var nodeValues, propertyValue;
      console.log("FamousPropertySetter::width");
      propertyValue = layer._properties.width;
      console.log("propertyValue: " + propertyValue);
      nodeValues = layer._element.getAbsoluteSize();
      if (nodeValues != null) {
        return layer._element.setAbsoluteSize(propertyValue, nodeValues[1], nodeValues[2]);
      }
    },
    height: function(layer) {
      var nodeValues, propertyValue;
      console.log("FamousPropertySetter::height");
      propertyValue = layer._properties.height;
      console.log("propertyValue: " + propertyValue);
      nodeValues = layer._element.getAbsoluteSize();
      if (nodeValues != null) {
        return layer._element.setAbsoluteSize(nodeValues[0], propertyValue, nodeValues[2]);
      }
    },
    originX: function(layer) {
      var originValues, propertyValue;
      console.log("FamousPropertySetter::originX");
      propertyValue = layer._properties.originX;
      console.log("propertyValue: " + propertyValue);
      originValues = layer._element.getOrigin();
      console.log("originValues:");
      console.log(originValues);
      return layer._element.setOrigin(propertyValue, originValues[1], originValues[2]);
    },
    originY: function(layer) {
      var originValues, propertyValue;
      propertyValue = layer._properties.originY;
      originValues = layer._element.getOrigin();
      console.log("originValues:");
      console.log(originValues);
      return layer._element.setOrigin(originValues[0], propertyValue, originValues[2]);
    },
    x: function(layer) {
      var nodeValues, propertyValue;
      console.log("FamousPropertySetter::x");
      propertyValue = layer._properties.x;
      nodeValues = layer._element.getPosition();
      console.log("nodeValues:");
      console.log(nodeValues);
      console.log("propertyValue: " + propertyValue);
      return layer._element.setPosition(propertyValue, layer._properties.y, layer._properties.z);
    },
    y: function(layer) {
      var nodeValues, propertyValue;
      console.log("FamousPropertySetter::y");
      propertyValue = layer._properties.y;
      nodeValues = layer._element.getPosition();
      console.log("nodeValues:");
      console.log(nodeValues);
      console.log("propertyValue: " + propertyValue);
      return layer._element.setPosition(layer._properties.x, propertyValue, layer._properties.z);
    },
    z: function(layer) {
      var nodeValues, propertyValue;
      console.log("FamousPropertySetter::z");
      propertyValue = layer._properties.z;
      nodeValues = layer._element.getPosition();
      console.log("nodeValues:");
      console.log(nodeValues);
      console.log("propertyValue: " + propertyValue);
      return layer._element.setPosition(layer._properties.x, layer._properties.y, propertyValue);
    },
    scale: function(layer) {
      var nodeValues, propertyValue;
      console.log("FamousPropertySetter::scale");
      propertyValue = layer._properties.scale;
      nodeValues = layer._element.getScale();
      return layer._element.setScale(propertyValue, propertyValue, propertyValue);
    },
    rotationX: function(layer) {
      var nodeValues, propertyValue;
      console.log("FamousPropertySetter::rotationX");
      propertyValue = layer._properties.rotationX;
      nodeValues = layer._element.getRotation();
      return layer._element.setRotation(propertyValue, nodeValues[1], nodeValues[2]);
    },
    rotationY: function(layer) {
      var nodeValues, propertyValue;
      console.log("FamousPropertySetter::rotationY");
      propertyValue = layer._properties.rotationY;
      nodeValues = layer._element.getRotation();
      return layer._element.setRotation(nodeValues[0], propertyValue, nodeValues[2]);
    },
    rotationZ: function(layer) {
      var nodeValues, propertyValue;
      console.log("FamousPropertySetter::rotationZ");
      propertyValue = layer._properties.rotationZ * Math.PI / 180;
      nodeValues = layer._element.getRotation();
      return layer._element.setRotation(nodeValues[0], nodeValues[1], propertyValue);
    },
    backgroundColor: function(layer) {
      var propertyValue;
      propertyValue = layer._properties.backgroundColor;
      return layer._element.setProperty("backgroundColor", propertyValue);
    }
  };

  module.exports = FamousPropertySetter;

}).call(this);
