// Generated by CoffeeScript 1.9.2
(function() {
  var Engine, FamousWindow, Logger, famous,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  famous = require("famous");

  Engine = famous.core.FamousEngine;

  Logger = require('./Logger');

  FamousWindow = (function() {
    function FamousWindow(options) {
      this.createNode = bind(this.createNode, this);
      options = options || {};
      Logger.log('FamousWindow constructor called');
      Logger.log('Creating scene...');
      this.scene = Engine.createScene();
      this.isRootWindow = options.isRootWindow || false;
    }

    FamousWindow.prototype.createNode = function() {
      var newNode;
      newNode = this.scene.addChild();
      return newNode;
    };

    return FamousWindow;

  })();

  module.exports = FamousWindow;

}).call(this);
