// Generated by CoffeeScript 1.9.2
(function() {
  var FamousPropertySetter;

  FamousPropertySetter = {
    visible: function(layer) {
      var propertyValue;
      propertyValue = layer._properties.visible;
      if (propertyValue) {
        return layer._element.setProperty("display", "block");
      } else {
        return layer._element.setProperty("display", "none");
      }
    },
    opacity: function(layer) {
      var propertyValue;
      propertyValue = layer._properties.opacity;
      return layer._node.setOpacity(propertyValue);
    },
    index: function(layer) {
      var propertyValue;
      propertyValue = layer._properties.index;
      return layer._element.setProperty("zIndex", propertyValue);
    },
    color: function(layer) {
      var propertyValue;
      propertyValue = layer._properties.color;
      return layer._element.setProperty("color", propertyValue);
    },
    width: function(layer) {
      var nodeValues, propertyValue;
      propertyValue = layer._properties.width;
      nodeValues = layer._node.getAbsoluteSize();
      return layer._node.setAbsoluteSize(propertyValue, nodeValues[1], nodeValues[2]);
    },
    height: function(layer) {
      var nodeValues, propertyValue;
      propertyValue = layer._properties.height;
      nodeValues = layer._node.getAbsoluteSize();
      return layer._node.setAbsoluteSize(nodeValues[0], propertyValue, nodeValues[2]);
    },
    originX: function(layer) {
      var originValues, propertyValue;
      propertyValue = layer._properties.originX;
      originValues = layer._node.getOrigin();
      return layer._node.setOrigin(propertyValue, originValues[1], originValues[2]);
    },
    originY: function(layer) {
      var originValues, propertyValue;
      propertyValue = layer._properties.originY;
      originValues = layer._node.getOrigin();
      return layer._node.setOrigin(originValues[0], propertyValue, originValues[2]);
    },
    x: function(layer) {
      var nodeValues, propertyValue;
      propertyValue = layer._properties.x;
      nodeValues = layer._node.getPosition();
      return layer._node.setPosition(propertyValue, nodeValues[1], nodeValues[2]);
    },
    y: function(layer) {
      var nodeValues, propertyValue;
      propertyValue = layer._properties.y;
      nodeValues = layer._node.getPosition();
      return layer._node.setPosition(nodeValues[0], propertyValue, nodeValues[2]);
    },
    z: function(layer) {
      var nodeValues, propertyValue;
      propertyValue = layer._properties.z;
      nodeValues = layer._node.getPosition();
      return layer._node.setPosition(nodeValues[0], nodeValues[1], propertyValue);
    },
    scale: function(layer) {
      var nodeValues, propertyValue;
      propertyValue = layer._properties.scale;
      nodeValues = layer._node.getScale();
      return layer._node.setScale(propertyValue, propertyValue, propertyValue);
    },
    rotationZ: function(layer) {
      var nodeValues, propertyValue;
      propertyValue = layer._properties.rotationZ * Math.PI / 180;
      nodeValues = layer._node.getRotation();
      return layer._node.setRotation(0, 0, propertyValue);
    },
    backgroundColor: function(layer) {
      var propertyValue;
      propertyValue = layer._properties.backgroundColor;
      return layer._element.setProperty("background-color", propertyValue);
    }
  };

  module.exports = FamousPropertySetter;

}).call(this);
