// Generated by CoffeeScript 1.9.2
(function() {
  var Layer, layerA, layerB;

  Layer = require("./Layer");

  layerA = new Layer({
    width: 260,
    height: 260,
    backgroundColor: "green"
  });

  layerB = new Layer({
    width: 60,
    height: 60,
    backgroundColor: "#2DD7AA",
    scale: 1,
    borderRadius: 3
  });

  layerB.superlayer = layerA;

  layerB.centerX();

  layerB.x = 10;

}).call(this);
