// Generated by CoffeeScript 1.9.2
(function() {
  var Layer, layerA, layerB;

  Layer = require("./Layer");

  layerA = new Layer({
    width: 60,
    height: 60,
    backgroundColor: "#2DD7AA"
  });

  layerA.borderRadius = 5;

  layerA.x = 300;

  layerA.y = 200;

  layerB = new Layer({
    width: 80,
    height: 80,
    backgroundColor: "green",
    x: 440
  });

}).call(this);
