// Generated by CoffeeScript 1.9.2
(function() {
  var LayerId;

  LayerId = (function() {
    function LayerId() {}

    LayerId.currentId = 0;

    LayerId.generateNewId = function() {
      this.currentId += 1;
      return this.currentId;
    };

    return LayerId;

  })();

  module.exports = LayerId;

}).call(this);
