// Generated by CoffeeScript 1.9.2
(function() {
  var Logger;

  Logger = (function() {
    function Logger() {}

    Logger.log = function(msg) {
      return console.log(msg);
    };

    return Logger;

  })();

  module.exports = Logger;

}).call(this);
