// Generated by CoffeeScript 1.9.2
(function() {
  var Context, Utils, printContext, printLayer,
    slice = [].slice;

  Utils = require("./Utils");

  Context = require("./Context").Context;

  "\nTodo:\n- Better looks\n- Resizable\n- Live in own space on top of all Framer stuff\n";

  printContext = null;

  printLayer = null;

  exports.print = function() {
    var args;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    if (!printContext) {
      printContext = new Context({
        name: "Print"
      });
    }
    printContext.run(function() {
      var printNode, printPrefix, update;
      if (!printLayer) {
        printLayer = new Layer;
        printLayer.scrollVertical = true;
        printLayer.ignoreEvents = false;
        printLayer.html = "";
        printLayer.style = {
          "font": "12px/1.35em Menlo",
          "color": "rgba(0,0,0,.7)",
          "padding": "8px",
          "padding-bottom": "30px",
          "border-top": "1px solid #d9d9d9"
        };
        printLayer.opacity = 0.9;
        printLayer.style.zIndex = 999;
        printLayer.visible = true;
        printLayer.backgroundColor = "white";
        update = function() {
          printLayer.width = window.innerWidth;
          printLayer.height = 160;
          return printLayer.maxY = window.innerHeight;
        };
        update();
        printContext.eventManager.wrap(window).addEventListener("resize", update);
      }
      printPrefix = "» ";
      printNode = document.createElement("div");
      printNode.innerHTML = _.escape(printPrefix + args.map(Utils.inspect).join(", ")) + "<br>";
      printNode.style["-webkit-user-select"] = "text";
      printNode.style["cursor"] = "auto";
      return printLayer._element.appendChild(printNode);
    });
    return Utils.delay(0, function() {
      return printLayer._element.scrollTop = printLayer._element.scrollHeight;
    });
  };

}).call(this);
