// Generated by CoffeeScript 1.9.2
(function() {
  var Layer,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Layer = require("./Layer").Layer;

  exports.VideoLayer = (function(superClass) {
    extend(VideoLayer, superClass);

    function VideoLayer(options) {
      if (options == null) {
        options = {};
      }
      this.player = document.createElement("video");
      this.player.setAttribute("webkit-playsinline", "true");
      this.player.style.width = "100%";
      this.player.style.height = "100%";
      VideoLayer.__super__.constructor.call(this, options);
      this.player.on = this.player.addEventListener;
      this.player.off = this.player.removeEventListener;
      this.video = options.video;
      this._element.appendChild(this.player);
    }

    VideoLayer.define("video", {
      get: function() {
        return this.player.src;
      },
      set: function(video) {
        return this.player.src = video;
      }
    });

    return VideoLayer;

  })(Layer);

}).call(this);
